spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    hibernate:
      ddl-auto: none
  application:
    name: SWARM-Back
  datasource:
    password: ${BDD_USER_PASSWORD:password}
    username: ${BDD_USER:user}
    url: ${BDD_URL:jdbc:postgresql://localhost:5432/swarm}

org:
  chessmooc:
    swarm:
      front:
        service:
          url: ${FRONT_SERVICE_URL:http://localhost:3000}
      back:
        service:
          url: ${BACK_SERVICE_URL:http://localhost:8080}

server:
  port: ${BACK_SERVICE_PORT:8080}
